version: '3'

services:
  jira:
    image: atlassian/jira-software:9.5.0
    container_name: jira
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
    networks:
      - mynetwork

  confluence:
    image: atlassian/confluence-server:8.6-jdk17
    container_name: confluence
    ports:
      - "8090:8090"
    networks:
      - mynetwork

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: yahav
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: servertest
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  gogs:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "3000:3000"
      - "10022:22"
    networks:
      - mynetwork
    volumes:
      - gogs_data:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  gogs_data:
